Comics = [
    { }, /* placeholder for nonexistent comic zero */
    { "alt":"This is the way all physics works -- it changes as soon as you prove it wrong.", "title":"It's Only Real While We Say It Is" },
    { "alt":"Andrew was going to tell me what to put here, but then he disappeared.", "title":"The Third Postulate" },
    { "alt":"Yes, Pi in the Sky. Now you see what bad people we are.", "title":"The Greek Letter Series - #1" },
    { "alt":"Merrily merrily merrily merrily / Life is but a dream...", "title":"The Greek Letter Series - #2" },
    { "alt":"\"Ay, 'tis but a scratch. Ask for me tomorrow, and you shall find me a grave man.\"", "title":"The Greek Letter Series - #3" },
    { "alt":"Yes, we realize the table looks like a physical improbability. But we assure you, it's securely bolted to the floor and made of balsa wood to boot.", "title":"The Greek Letter Series - #4" },
    { "alt":"socks? I asked for a wii...", "title":"Schrödinger's Santa" },
    { "alt":"Mr. Herman built Cyclops his laser-shielding goggles using RAW PHYSICS", "title":"'The True Meaning of Xmas'" },
    { "alt":"Oh yeah, and the Physics C pulley is on a sphere traveling the speed of light around Jupiter.", "title":"A Slight Difference" },
    { "alt":"Recent research shows that while 52% of participants in a New Year's resolutions study were confident of success with their goals, only 12% actually achieved them...(pwned)", "title":"New Year's Resolutions" },
    { "alt":"It's all just a ploy to collect more traffic violation fines.", "title":"Signs" },
    { "alt":"\"Blasphe-meeeeee, blasphe-youuuuu, blasphe-everyone in the room...\"", "title":"Snow Day" },
    { "alt":"DOWN WITH BIG BROTHER DOWN WITH BIG BROTHER DOWN WITH BIG BROTHER DOWN WITH BIG BROTHER DOWN WITH BIG BROTHER DOWN WITH BIG BROTHER", "title":"1984" },
    { "alt":"In the 3rd panel, Dave is scribbling down derivatives. Ba-DUM DISHHH", "title":"Boxes" },
    { "alt":"Watch us on It's Academic! Go to tinyurl.com/itsacademic", "title":"Do's and Don'ts on It's Academic" },
    { "alt":"Hey! What are you doing with that match?", "title":"Rocket Science" },
    { "alt":"But for just one moment, Kurt Warner thought he was invincible", "title":"Conservation of Momentum" },
    { "alt":"They're just better than us at it", "title":"Networking" },
    { "alt":"Natural 20!", "title":"D&D" },
    { "alt":"Which means 1 Du is about 5.83 Joules", "title":"Units" },
    { "alt":"Use algebra (solve for i)", "title":"Valentine's Day" },
    { "alt":"The instantaneous change of a human over a time interval that approaches zero", "title":"Derivative Series #1 - The Human Derivative" },
    { "alt":"This isn't your grandma's Function Grapher... THE FUNCTION GRAPHER 2000!!", "title":"Derivative Series #2 - Integrating Humans" },
    { "alt":"The first and last time anybody uttered the words 'This oversized novelty pencil saved my life!'", "title":"Derivative Series #3 - The Experiment Backfires" },
    { "alt":"That dude in front's gonna have some pretty weird notes on this lecture.", "title":"Derivative Series #4 - Calling in the Cavalry" },
    { "alt":"Wonder what Andrew's doing . . .", "title":"Derivative Series #5 - Zeno's Paradox" },
    { "alt":"Division by zero -- do NOT try this at home!", "title":"Derivative Series #6 - Undefined" },
    { "alt":"Seriously, it could work!", "title":"Derivative Series #7 - It's Not Over Yet" },
    { "alt":"Victory!", "title":"Derivative Series #8 - Payback Time" },
    { "alt":"Dave made this comic instead of sleeping last night", "title":"Underappreciated" },
    { "alt":"A coonskin hat is really the most sensible choice for this setting.", "title":"Simple English" },
    { "alt":"WHAT!? HE TOOK A STUDY HALL!?", "title":"College Admissions" },
    { "alt":"If all else fails, ask it to open the pod bay doors", "title":"How to: Blow an Android's Cover" },
    { "alt":"Think this is bad? Wait until you see how they enforce HOV . . . ", "title":"Enforced By Aircraft" },
    { "alt":"Dave Kilian wants to be your friend [Accept] [Ignore] ", "title":"Facebook in Real Life" },
    { "alt":"I mean I understand their concern and all... Earth's pretty important ", "title":"Environmentalists" },
    { "alt":"Print this comic out at put it in someone's tip jar. It'll make their day. ", "title":"Tips" },
    { "alt":"When the crowd starts booing, you know you're in trouble", "title":"Guitar Hero ≠ Real Life" },
    { "alt":"You won't know if Schrödinger's cat is still following you until you turn around and look", "title":"Fudge Equation" },
    { "alt":"'Stewardesses' is the longest word in the English language that you can type using only your left hand ", "title":"Stewardess" },
    { "alt":"Phew! For second there I thought they were going to say motheeEEY LOOK A VECTOR!", "title":"Vectors on a Plane" },
    { "alt":"ABANDON SHIP!!", "title":"Checking for Sanity" },
    { "alt":"OK . . . S-C-R-E-W-O-F-F", "title":"Spelling Bee" },
    { "alt":"Excuse me ma'am, but I don't see how wineglasses are going to help my vision", "title":"Vision Test" },
    { "alt":"So ... what's the deal with audience members heckling us poor comedians? ", "title":"Comedians" },
    { "alt":"By reading this alt text, you agree to refrain from posting disparaging remarks about this comic or any other ", "title":"Diplomacy" },
    { "alt":"They lost their connection.", "title":"Dr. Phil" },
    { "alt":"Give us this day our daily Peebles Lab", "title":"21st Century Religion" },
    { "alt":"Can you solve me now?", "title":"Service" },
    { "alt":"50 Comics! Peebles Lab is on a roll!", "title":"How We Roll" },
    { "alt":"If your roommate routinely plays video games, it can lower your GPA by as much as 0.6 (ask a scientist!) ", "title":"Study Habits" },
    { "alt":"Gah, they are just so tricky. And the volume ones? Crazy!", "title":"Dr. Phil, Part Two" },
    { "alt":"BTW we also fired all your missiles", "title":"Hackers" },
    { "alt":"Peebles Lab: Your daily recommended allowance of low-blow puns.", "title":"Ill Bill" },
    { "alt":"Doesn't have the same ring to it though", "title":"Reasonable Goals" },
    { "alt":"So constructive it's destructive!", "title":"Destructive Interference" },
    { "alt":"Not sure what is going to replace the ion source though... ", "title":"Old School Analysis" },
    { "alt":"What was that guy's problem?", "title":"Methods" },
    { "alt":"No wait I like kittens too! awww... ", "title":"Free Buddy Diagram" },
    { "alt":"Ugh no wait, we have that list around here somewhere ...", "title":"Nobel Prize" },
    { "alt":"Jim *Peebles*, a Physics professor at Princeton predicted cosmic background radiation before there was empirical evidence for it! ", "title":"Push Button" },
    { "alt":"Stress cannot be created nor destroyed (as much as you wish it could be!)", "title":"Le Chatelier's Principle of Exam Stress" },
    { "alt":"The answer is always C. Or 42 depending on the circumstances.", "title":"How to: Do Physics Like the Pros" },
    { "alt":"One Problem to rule them all, one way to solve them. One force to cause them all and on the ramp revolve them. ", "title":"The Only Problem" },
    { "alt":"How does Newton like them apples? ", "title":"Physics Greetings" },
    { "alt":"Mr. Herman cooks his Thanksgiving turkey with RAW PHYSICS", "title":"The True Meaning of Thanksgiving " },
    { "alt":"ARE YOU SRS?! ", "title":"Advanced Calculator" },
    { "alt":"In other news, a new report indicates there may indeed be radicals in the White House...", "title":"Complex Issues" },
    { "alt":"Maybe if they just learned calculus... maybe... ", "title":"Weather Models" },
    { "alt":"Don't complain Isaac, Marie Curie got a bacteria sample.", "title":"Genius Gifts" },
    { "alt":"Better luck next year! ", "title":"New Year's Plans" },
    { "alt":"We've decided to add features from the ever-popular site, Wikipedia! Try editing your friend's profiles today! ", "title":"Things We Hope Won't Change in 2010" },
    { "alt":"So perfect, so noble.", "title":"Gasanova" },
    { "alt":"After all, E does equal Mc squared", "title":"McPhysics" },
    { "alt":"To keep the doctor away, follow recommended dosage (one daily).", "title":"Apple: A Study" },
    { "alt":"Uhh... no your *other* right hand. ", "title":"Physics Teachers' Top Pet Peeves" },
    { "alt":"It's a bird, it's a plane, no, it's a vector field! ", "title":"The Intrepid Adventures of Integral Man and Sigma Boy" },
    { "alt":"Coulombus made his discovery, and the world was forever charged. ", "title":"Christopher Coulombus" },
    { "alt":"But if you do, we want royalties.", "title":"Suspect Autocomplete" },
    { "alt":"... (while flying my homemade rocket to the moon)", "title":"Spring Break" },
    { "alt":"Annnnnd boom goes the dynamite ", "title":"Mythbusters" },
    { "alt":"I know what you're thinking: Oh my gosh was the flash drive harmed? Luckily no, the metal exterior of the drive works as a Faraday's Cage.", "title":"Illegal Operation" },
    { "alt":"Physics: the ever-present backseat driver", "title":"Lifesaver" },
    { "alt":"Sometimes your greatest strength is your greatest weakness", "title":"Strength" },
    { "alt":"This intimate affinity will survive heated times: up to 2575 degrees Fahrenheit! ", "title":"unION" },
    { "alt":"Their relationship was dead in the water. ", "title":"unION, Part 2" },
    { "alt":"Be happy we left AC/DC alone", "title":"Science Punks" },
    { "alt":"Also, Dad, you realize how incredibly racist Halo is to aliens, right?", "title":"Retro Gaming" },
    { "alt":"This is how FDR kept getting re-elected", "title":"Census 2010" },
    { "alt":"Jokes aside, we really hope for progress in the Gulf", "title":"Poor Planning" },
    { "alt":"Think we're paying royalties for these songs? Dream On. ", "title":"Times When It's Not Appropriate to Burst Into Song" },
    { "alt":"Video response posted by Mozart", "title":"ThyTube" },
    { "alt":"What we've got here is a failure to commiserate. ", "title":"Communication Breakdown" },
    { "alt":"Don't worry if you haven't seen Inception -- we didn't spoil anything.", "title":"Galileo's Totem" },
    { "alt":"'Sir, put that down! That's expensive government research!'", "title":"LHC" },
    { "alt":"Thanks to Brendan Neyland for writing the dialog for this comic!", "title":"Fill-in-the-Dialog Contest" },
    { "alt":"If you see two lines that could be connected to make a panel, you are doomed to be a webcomic author. ", "title":"Career Choices" },
    { "alt":"Mostly because it's really easy and I'm not very good at math.", "title":"The Most Interesting Man in the World" },
    { "alt":"Hi, yeah so the X button on my controller is broken...", "title":"Cutscenes" },
    { "alt":"100 comics and still stuck on the same joke!", "title":"Proofs" },
];
